version: '3.8'

services:

  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: userservice-smartlogistics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build: ./user-service-smartlogistics
    container_name: user-service
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8080"

volumes:
  postgres_data:
